export { default as Hero } from './hero1'
export { default as Hero2 } from './hero2'
export * from './left-bar'
export * from './second-hero'
export * from './hero'
export * from './third-hero'
export * from './forth-hero'
export * from './apple'